    create table album (
       id int8 generated by default as identity,
        description varchar(255) not null,
        artist_id int8,
        primary key (id)
    );

    create table artist (
       id int8 generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    alter table if exists album
       add constraint fk_album_artist
       foreign key (artist_id)
       references artist;